### ISSUE TITLE
Re-naming of Trie Class

### ISSUE THREAD

**Issue by NIC619** [ApeWorX/py-trie#13]
### What was wrong?
If binary trie is added into `trie.py` as `BinaryTrie` class, should we re-name original `Trie` class to, like `MerkleTrie`, `PatriciaTrie`, `MerklePatriciaTrie`?

### What did you expect it to do?
perhaps we can have both `BinaryTrie` and re-named `Trie` in `trie.py` so people can tell the difference but keep the original `Trie` reference in `__init__.py` like this
```
from .trie import (  # noqa: F401
    MerklePatriciaTrie as Trie,
    BinaryTrie,
)
```
so that the existing codes implemented with the original Merkle Patricia Trie with `from trie import Trie` don't require any change

**Comment by pipermerriam** [comment]
I think I like `PatriciaTrie` but I'm also ok with `MerklePatriciaTrie`.

I'd like to create a `Trie` class that subclasses `MerklePatriciaTrie` and raises a `DeprecationWarning` so that this upgrade can happen smoothly.  That way we'll have `BinaryTrie`, `Trie` and `PatriciaTrie` all importable from the main module.  We'll phase out the `Trie` class in a few months once there's been time to update any dependent codebases.

**Comment by NIC619** [comment]
Sounds good to me. Definitely a more graceful approach.
`PatriciaTrie` +1

**Comment by hwwhww** [comment]
How about as @vbuterin suggested: `BinaryTrie` and `HexaryTrie` (they're both Merkle Patricia Tries).

**Comment by NIC619** [comment]
yeah, that will do 
I mistake patricia trie for hexary trie
