### ISSUE TITLE
Import error with eth-hash

### ISSUE THREAD

**Issue by davebryson** [ApeWorX/py-trie#50]
* Version: 1.3.4
* Python: 3.6
* OS: osx

### What was wrong?
After installing trie via pip, when you attempt to use the trie it throws the error:
```
ImportError: None of these hashing backends are installed: ['pycryptodome', 'pysha3'].
Install with `pip install eth-hash[pycryptodome].
```

It appears `pip install` is missing dependencies in `eth-hash`

#### Code to reproduce the error
To reproduce the error, simply try to import HexaryTrie: `from trie import HexaryTrie`

**Comment by pipermerriam** [comment]
This is actually intentional. Since `py-trie` is a low level library we don't make any assumptions about what hashing background you want to use.  You can either install as it states in the error message using `pip install eth-hash[pycryptodome]` or `pip install eth-hash[pysha3]` or you can manually specify the `pycryptodome` or `pysha3` dependency yourself.

**Comment by davebryson** [comment]
Ahhhh,  ok thanks.
